page_analyzer/models/db.py
import datetime
import os

import psycopg2
from dotenv import load_dotenv
from psycopg2.extras import RealDictCursor

load_dotenv()


class DBConnection:
    def __init__(self):
        self.database_url = os.getenv("DATABASE_URL")
        self.conn = psycopg2.connect(
            self.database_url,
            cursor_factory=RealDictCursor
        )

    def __enter__(self):
        with self.conn as conn:
            return conn.cursor()

    def __exit__(self, type, value, traceback):
        self.conn.commit()


class UrlsRepository:
    def __init__(self):
        self.cursor = DBConnection()

    def get_urls(self):
        query = """
            SELECT
                urls.id AS id,
                urls.name AS name,
                CAST(last_checks.created_at AS DATE) AS last_check,
                last_checks.status_code AS status_code
            FROM  urls
            LEFT JOIN (
                SELECT
                    max_checks.url_id AS url_id,
                    max_checks.created_at AS created_at,
                    checks.status_code AS status_code
                FROM (SELECT
                        url_id,
                        MAX(created_at) AS created_at
                    FROM url_checks
                    GROUP BY url_id) AS max_checks
                INNER JOIN url_checks AS checks ON
                    max_checks.url_id=checks.url_id
                WHERE max_checks.created_at=checks.created_at) AS last_checks ON
                urls.id=last_checks.url_id
            ORDER BY urls.created_at DESC;"""
        with self.cursor as curs:
            curs.execute(query)
            result = curs.fetchall()
        return result
        
    def find_url_by_id(self, id):
        query = """
            SELECT 
                id,
                name,
                CAST(created_at AS DATE)
            FROM urls
            WHERE id=%(id)s;"""
        query_kwargs = {'id': id}
        with self.cursor as curs:
            curs.execute(query, query_kwargs)
            result = curs.fetchone()
        return result
    
    def find_url_by_name(self, name):
        query = """
            SELECT 
                id,
                name,
                CAST(created_at AS DATE)
            FROM urls
            WHERE name=%(name)s;"""
        query_kwargs = {'name': name}
        with self.cursor as curs:
            curs.execute(query, query_kwargs)
            result = curs.fetchone()
        return result

    def save_url(self, url):
        query = """
            INSERT INTO urls (name, created_at)
            VALUES (%(name)s, %(created_at)s) RETURNING id;"""
        query_kwargs = {
            'name': url,
            'created_at': datetime.datetime.now()
        }
        with self.cursor as curs:
            curs.execute(query, query_kwargs)
            id = curs.fetchone()
        return id | query_kwargs

    def get_url_checks(self, url_id):
        query = """SELECT
                    id,
                    status_code,
                    h1,
                    title,
                    description,
                    CAST(created_at AS DATE)   
                FROM url_checks
                WHERE url_id=%(url_id)s
                ORDER BY url_checks.created_at DESC"""
        query_kwargs = {"url_id": url_id}
        with self.cursor as curs:
            curs.execute(query, query_kwargs)
            result = curs.fetchall()
        return result
    
    def check_save(self, check):
        query = """
            INSERT INTO url_checks (url_id, created_at, status_code,
                h1, title, description)
            VALUES (%(url_id)s, %(created_at)s, %(status_code)s,
                %(h1)s, %(title)s, %(description)s) RETURNING id;"""
        query_kwargs = {
            'url_id': check.url_id,
            'status_code': check.status_code,
            'h1': check.h1,
            'title': check.title,
            'description': check.description,
            'created_at': datetime.datetime.now()
        }
        with self.cursor as curs:
            curs.execute(query, query_kwargs)
            id = curs.fetchone()
        return id | query_kwargs

page_analyzer/models/models.py
from dataclasses import dataclass
from typing import Optional


@dataclass
class Url:
    id: Optional[int] = None
    name: Optional[str] = None
    created_at: Optional[str] = None
    last_check: Optional[str] = None
    status_code: Optional[str] = None


@dataclass
class UrlCheck:
    id: Optional[int] = None
    url_id: Optional[int] = None
    status_code: Optional[int] = None
    h1: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    created_at: Optional[str] = None

page_analyzer/__init__.py
from page_analyzer.app import app

__all__ = (
    'app'
)

page_analyzer/app.py
import os

from dotenv import load_dotenv
from flask import Flask


def create_app():
    load_dotenv()
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

    from page_analyzer.views import index, not_found
    app.register_blueprint(index)
    app.register_error_handler(404, not_found)

    return app


app = create_app()


if __name__ == "__main__":
    app.run()

page_analyzer/views.py
from urllib.parse import urlparse

import validators
from flask import (
    Blueprint,
    flash,
    get_flashed_messages,
    redirect,
    render_template,
    request,
    url_for,
)

from page_analyzer.http import get_http_response
from page_analyzer.models.db import UrlsRepository
from page_analyzer.models.models import Url, UrlCheck

index = Blueprint('index', __name__, url_prefix='/')


@index.route('/')
def main_page():
    messages = get_flashed_messages(with_categories=True)
    return render_template('index.html', messages=messages)


@index.route('/urls', methods=["GET"])
def urls_get():
    messages = get_flashed_messages(with_categories=True)

    urls = UrlsRepository().get_urls()
    sites = [Url(**url) for url in urls]

    return render_template('urls/index.html',
                           sites=sites,
                           messages=messages)


@index.route('/urls', methods=["POST"])
def urls_post():
    url = request.form.get('url')
    if validators.url(url) is not True:
        flash("Некорректный URL", "alert alert-danger")
        messages = get_flashed_messages(with_categories=True)
        return render_template('index.html', messages=messages, value=url), 422
    
    domain = urlparse(url). \
        _replace(path='', params='', query='', fragment='').geturl()
    
    url_in_db = UrlsRepository().find_url_by_name(domain)
    
    if url_in_db:
        url = Url(**url_in_db)
        flash("Страница уже существует.", "alert alert-info")
        return redirect(url_for('index.url_info', id=url.id))
    
    return redirect(url_for('index.urls_add_new', domain=domain), 307)


@index.route('/urls/add', methods=["POST"])
def urls_add_new():
    domain = request.args.get('domain')
    
    saved_url = UrlsRepository().save_url(domain)
    new_url = Url(**saved_url)
    
    flash("Страница успешно добавлена.", "alert alert-success")
    return redirect(url_for("index.url_info", id=new_url.id))


@index.route('/urls/<id>', methods=['GET'])
def url_info(id):
    messages = get_flashed_messages(with_categories=True)

    url_in_db = UrlsRepository().find_url_by_id(id)
    url = Url(**url_in_db)
    
    if url.id:
        checks_in_db = UrlsRepository().get_url_checks(url.id)
        checks = [UrlCheck(**check) for check in checks_in_db]
        return render_template("urls/url_check.html",
                            messages=messages,
                            url=url,
                            checks=checks)
    return render_template('404.html'), 404


@index.route('/urls/<id>/check', methods=['POST'])
def url_check(id):
    url_in_db = UrlsRepository().find_url_by_id(id)
    url = Url(**url_in_db)
    http_response = get_http_response(url.name)
    if not http_response.get('status_code'):
        flash("Произошла ошибка при проверке", "alert alert-danger")
        return redirect(url_for("index.url_info", id=url.id))
    
    url_info = UrlCheck(url_id=url.id, **http_response)
    UrlsRepository().check_save(url_info)
    flash("Страница успешно проверена", "alert alert-success")
    return redirect(url_for("index.url_info", id=url_info.url_id))
    

@index.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

page_analyzer/templates/index.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Анализатор страниц by Fomine Andrei{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
      <nav class="navbar align-items-baseline navbar-expand-md bg-dark px-3">
        <a class="navbar-brand text-light" href="{{ url_for("index.main_page") }}">Анализатор страниц</a>
        <div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for("index.urls_get") }}" style="color: gray;">Сайты</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    {% if messages %}
      <ul class="list-unstyled">
      {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    <main class="flex-grow-1">
      {% block main %}
      <div class="container-fluid container-lg mt-5">
        <div class="row">
          <div class="col-12 col-lg-8 mx-auto border rounded p-3 bg-light">
            <h1 class="display-3">Анализатор страниц</h1>
            <h2 class="lead">Бесплатно проверяйте сайты на SEO-пригодность</h2>
            <div class="container-fluid mx-0 p-0">
              <form class="row my-3 mx-0 p-0" action="{{ url_for("index.urls_post") }}" method="POST">
                <label class="visually-hidden">Введите адрес сайта</label>
                <input name="url" type="text" class="col-10 col-lg-7 form-control-lg rounded me-3 mt-1 text-center text-lg-start" required placeholder="https://example.com" value="{% if value %}{{ value }}{% endif %}">
                <input type="submit" class="col-10 col-lg-4 col-xl-3 btn btn-primary px-3 mt-1 text-uppercase" value="Проверить">
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </main>
    <footer class="d-flex justify-content-center bg-secondary">
      <a class="p-2" href="https://vk.com/fomineandrei_adm">Fomine Andrei</a>
      <p class="px-2 pt-2 text-light">2025</p>
    </footer>
  </body>
</html>

page_analyzer/templates/urls/index.html
{% extends "index.html" %}


{% block title %}Сайты для анализа{% endblock %}


{% block main %}
<div class="container-fluid container-lg mt-3">
  <h1>Сайты</h1>
  <div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="urls">
      <thead>
        <tr style>
          <th scope="col">ID</th>
          <th scope="col">Имя</th>
          <th scope="col">Последняя проверка</th>
          <th scope="col">Код ответа</th>
        </tr>
      </thead>
      <tbody>
        {% if sites %}
        {% for site in sites %}
        <tr>
          <td>{{ site.id }}</td>
          <td><a href="{{ url_for('index.url_info', id=site.id) }}">{{ site.name }}</a></td>
          <td>{% if site.last_check %}{{ site.last_check }}{% endif %}</td>
          <td>{% if site.status_code %}{{ site.status_code }}{% endif %}</td>
        </tr>
        {% endfor %}
        {% endif %}
      </tbody>
    </table>
  </div>  
</div>
{% endblock %}

page_analyzer/templates/urls/url_check.html
{% extends "index.html" %}


{% block title %}Анализ страницы{% endblock %}


{% block main %}
<div class="container-fluid container-lg mt-3">
  <h1>Сайт: {{ url.url }}</h1>
  <div class="table-responsive mb-5">
    <table class="table table-bordered table-hover mb-4" data-test="urls">
      <tbody>
        <tr>
          <td scope="row">ID</td>
          <td>{{ url.id }}</td>
        </tr>
        <tr>
          <td scope="row">Имя</td>
          <td>{{ url.name }}</td>
        </tr>
        <tr>
          <td scope="row">Дата создания</td>
          <td>{{ url.created_at }}</td>
        </tr>
      </tbody>
    </table>
  </div> 
  <h2>Проверки</h2>
  <form class="my-3 mx-0 p-0" action="{{ url_for("index.url_check", id=url.id) }}" method="POST">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
  </form>
  <div class="table-responsive">
    <table class="table table-bordered table-hover" data-test="checks">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Код ответа</th>
          <th scope="col">h1</th>
          <th scope="col">title</th>
          <th scope="col">description</th>
          <th scope="col">Дата создания</th>
        </tr>
      </thead>
      <tbody>
        {% if checks %}
        {% for check in checks %}
        <tr>
          <td>{{ check.id }}</td>
          <td>{% if check.status_code %}{{ check.status_code }}{% endif %}</td>
          <td>{% if check.h1 %}{{ check.h1 }}{% endif %}</td>
          <td>{% if check.title %}{{ check.title }}{% endif %}</td>
          <td>{% if check.description %}{{ check.description }}{% endif %}</td>
          <td>{{ check.created_at }}</td>
        </tr>
        {% endfor %}
        {% endif %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}